### ISSUE TITLE
Loading large planes leads to server crashes

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-fpbioimage#16]
```
017-07-06 12:45:53,99

WARN - 2 WARN messages (Last worst: "protocol error: memory limit exceeded:")

WARN - 4 WARN messages (Last worst: "2017-07-06 12:45:53,993 ERROR [ django.request] (proc.27968) handle_uncaught_exception():256 Internal Server Error: /fpbioimage/imageStacks/881/000.png")
```

Planes are definitely being retrieved rather than tiles:

https://github.com/ome/omero-fpbioimage/blob/master/omero_fpbioimage/views.py#L74

```
omero=> select sizex, sizey, sizez, sizet, sizec from pixels where image = 881;
 sizex | sizey | sizez | sizet | sizec
-------+-------+-------+-------+-------
 49101 | 53202 |     1 |     1 |     3
(1 row)
```

**Comment by will-moore** [comment]
Seen again on demo server:

```
Internal Server Error: /fpbioimage/imageStacks/95355/000.png
Traceback (most recent call last):
  File "/opt/omero/web/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/omero/web/OMERO.web/lib/python/omeroweb/decorators.py", line 486, in wrapped
    retval = f(request, *args, **kwargs)
  File "/opt/omero/web/venv/lib/python2.7/site-packages/omero_fpbioimage/views.py", line 148, in fpbioimage_png
    jpeg_data = image.renderJpeg(the_z, 0, compression=0.9)
  File "/opt/omero/web/OMERO.web/lib/python/omero/gateway/__init__.py", line 7741, in wrapped
    return f(self, *args, **kwargs)
  File "/opt/omero/web/OMERO.web/lib/python/omero/gateway/__init__.py", line 9204, in renderJpeg
    self._pd, self._conn.SERVICE_OPTS)
  File "/opt/omero/web/OMERO.web/lib/python/omero/gateway/__init__.py", line 4703, in __call__
    return self.handle_exception(e, *args, **kwargs)
  File "/opt/omero/web/OMERO.web/lib/python/omeroweb/webclient/webclient_gateway.py", line 2127, in handle_exception
    e, *args, **kwargs)
  File "/opt/omero/web/OMERO.web/lib/python/omero/gateway/__init__.py", line 4700, in __call__
    return self.f(*args, **kwargs)
  File "/opt/omero/web/OMERO.web/lib/python/omero_api_RenderingEngine_ice.py", line 913, in renderCompressed
    return _M_omero.api.RenderingEngine._op_renderCompressed.invoke(self, ((_def, ), _ctx))
ApiUsageException: exception ::omero::ApiUsageException
{
    serverStackTrace = ome.conditions.ApiUsageException: 46514×70100 plane too large, cannot exceed 2^31 pixels
        at omeis.providers.re.RGBIntBuffer.<init>(RGBIntBuffer.java:63)
```
