### ISSUE TITLE
fpbioimage requests overly large planes

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-fpbioimage#28]
```
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero_fpbioimage/views.py", line 148, in fpbioimage_png
jpeg_data = image.renderJpeg(the_z, 0, compression=0.9)
....

2020-05-22 14:27:38,138 ERROR [ django.request] (proc.23371) handle_uncaught_exception():135 HTTP 500 <WSGIRequest: GET '/fpbioimage/imageStacks/120666/000.png'>
Traceback (most recent call last):
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 488, in wrapped
retval = f(request, *args, **kwargs)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero_fpbioimage/views.py", line 148, in fpbioimage_png
jpeg_data = image.renderJpeg(the_z, 0, compression=0.9)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 7789, in wrapped
return f(self, *args, **kwargs)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 9249, in renderJpeg
self._pd, self._conn.SERVICE_OPTS)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 4749, in __call__
return self.handle_exception(e, *args, **kwargs)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webclient/webclient_gateway.py", line 2126, in handle_exception
e, *args, **kwargs)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 4746, in __call__
return self.f(*args, **kwargs)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero_api_RenderingEngine_ice.py", line 913, in renderCompressed
return _M_omero.api.RenderingEngine._op_renderCompressed.invoke(self, ((_def, ), _ctx))
omero.ApiUsageException: exception ::omero::ApiUsageException
{
serverStackTrace = ome.conditions.ApiUsageException: 98304×57344 plane too large, cannot exceed 2^31 pixels
at omeis.providers.re.RGBIntBuffer.<init>(RGBIntBuffer.java:63)
at omeis.providers.re.RenderingStrategy.getIntBuffer(RenderingStrategy.java:186)

```

Seen today on demo.

**Comment by mtbc** [comment]
Could be worth reviewing in concert with #16.
